### ISSUE TITLE
Missing file entries when dropping from Firefox downloads

### ISSUE THREAD

**Issue by mattrossman** [donmccurdy/simple-dropzone#67]
Oftentimes I'll download a glTF file in Firefox and open https://gltf-viewer.donmccurdy.com/ to preview it, dragging the file straight from the downloads bar, only to be met with this error:

<img width="400" alt="alert dialog that says no .gltf or .glb asset found." src="https://user-images.githubusercontent.com/22670878/227662989-2c9566b7-55ae-4d4c-80a9-6092a51f8abb.png">

As a workaround, I have to first open my system file browser and drag from there, or use Chrome instead. I traced the issue down to this `simple-dropzone` dependency.

Running this demo locally, I notice that `entries` in `_onDrop` contains a `null` entry when dragged from the Firefox downloads bar.

<img width="274" alt="image" src="https://user-images.githubusercontent.com/22670878/227663578-25a00393-feb7-4028-87e3-b8cd6c097598.png">

Then when `_loadNextEntry` pops from the end of these entries, it thinks that it ran out of entries causing it to prematurely return before reaching the meaningful files.

https://github.com/donmccurdy/simple-dropzone/blob/3dfd00b13cf9c9354ce104bd2a8f56a5913fac8a/index.js#L150-L156

Indeed, if you change the JSDoc param signature of `_onDrop` from `Event` to `DragEvent`, VSCode indicates that `DataTransferItem.webkitGetAsEntry()` can return `null`:

<img width="612" alt="image" src="https://user-images.githubusercontent.com/22670878/227663646-9634583f-57c3-4f4b-b259-0e40bf358b4e.png">

This can be fixed by filtering out the null entries before the call to `_loadNextEntry`

**Comment by donmccurdy** [comment]
Wasn't aware of that issue – thank you!
