### ISSUE TITLE
Unhandled exception

### ISSUE THREAD

**Issue by gjcope** [donmccurdy/simple-dropzone#69]
Probably not an issue most of the time, but we have a custom DataTransferItem for dockable panels that users have accidently dragged to a dropzone which can result in an empty entries array, with https://github.com/donmccurdy/simple-dropzone/blob/e0f95a52e305c646d539cab2691062b6bb286325/index.js#L99 throwing an exception.

**Comment by donmccurdy** [comment]
Thanks @gjcope!

> custom DataTransferItem for dockable panels

I'm not sure how to test that and check that something reasonable happens for an empty array, would you be up for a PR on this?

**Comment by gjcope** [comment]
Sure, no problem.
